//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.SiteMinder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SiteMinder.ISiteminder")]
    public interface ISiteminder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRS", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRS(Test.SiteMinder.OTA_HotelResNotifRQ Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRS", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSResponse")]
        System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSError", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSErrorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRSError(Test.SiteMinder.OTA_HotelResNotifRQ Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSError", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSErrorResponse")]
        System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSErrorAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarning", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarningResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRSWarning(Test.SiteMinder.OTA_HotelResNotifRQ Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarning", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarningResponse")]
        System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSWarningAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarningAndError", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarningAndErrorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRSWarningAndError(Test.SiteMinder.OTA_HotelResNotifRQ Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarningAndError", ReplyAction="http://tempuri.org/ISiteminder/OTA_HotelResNotifRSWarningAndErrorResponse")]
        System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSWarningAndErrorAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class OTA_HotelResNotifRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HotelReservation[] hotelReservationsField;
        
        private string versionField;
        
        private string echoTokenField;
        
        private System.DateTime timeStampField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public HotelReservation[] HotelReservations {
            get {
                return this.hotelReservationsField;
            }
            set {
                this.hotelReservationsField = value;
                this.RaisePropertyChanged("HotelReservations");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class HotelReservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private POS pOSField;
        
        private UniqueID uniqueIDField;
        
        private RoomStay[] roomStaysField;
        
        private ResGlobalInfo resGlobalInfoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public POS POS {
            get {
                return this.pOSField;
            }
            set {
                this.pOSField = value;
                this.RaisePropertyChanged("POS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UniqueID UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
                this.RaisePropertyChanged("UniqueID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public RoomStay[] RoomStays {
            get {
                return this.roomStaysField;
            }
            set {
                this.roomStaysField = value;
                this.RaisePropertyChanged("RoomStays");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ResGlobalInfo ResGlobalInfo {
            get {
                return this.resGlobalInfoField;
            }
            set {
                this.resGlobalInfoField = value;
                this.RaisePropertyChanged("ResGlobalInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class POS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Source sourceField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class Source : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestorID requestorIDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestorID RequestorID {
            get {
                return this.requestorIDField;
            }
            set {
                this.requestorIDField = value;
                this.RaisePropertyChanged("RequestorID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class RequestorID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int typeField;
        
        private string codeField;
        
        private int recordIDField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
                this.RaisePropertyChanged("RecordID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class Warning : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int typeField;
        
        private string codeField;
        
        private int recordIDField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
                this.RaisePropertyChanged("RecordID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class Success : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class OTA_HotelResNotifRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Success successField;
        
        private HotelReservation[] hotelReservationsField;
        
        private Warning[] warningsField;
        
        private Error[] errorsField;
        
        private string versionField;
        
        private string echoTokenField;
        
        private System.DateTime timeStampField;
        
        private string resResponseTypeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Success Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public HotelReservation[] HotelReservations {
            get {
                return this.hotelReservationsField;
            }
            set {
                this.hotelReservationsField = value;
                this.RaisePropertyChanged("HotelReservations");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Warning[] Warnings {
            get {
                return this.warningsField;
            }
            set {
                this.warningsField = value;
                this.RaisePropertyChanged("Warnings");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResResponseType {
            get {
                return this.resResponseTypeField;
            }
            set {
                this.resResponseTypeField = value;
                this.RaisePropertyChanged("ResResponseType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class HotelReservationID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resID_TypeField;
        
        private string resID_ValueField;
        
        private string resID_SourceField;
        
        private string forGuestField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ResID_Type {
            get {
                return this.resID_TypeField;
            }
            set {
                this.resID_TypeField = value;
                this.RaisePropertyChanged("ResID_Type");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResID_Value {
            get {
                return this.resID_ValueField;
            }
            set {
                this.resID_ValueField = value;
                this.RaisePropertyChanged("ResID_Value");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResID_Source {
            get {
                return this.resID_SourceField;
            }
            set {
                this.resID_SourceField = value;
                this.RaisePropertyChanged("ResID_Source");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ForGuest {
            get {
                return this.forGuestField;
            }
            set {
                this.forGuestField = value;
                this.RaisePropertyChanged("ForGuest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class HotelReservationIDs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HotelReservationID hotelReservationIDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HotelReservationID HotelReservationID {
            get {
                return this.hotelReservationIDField;
            }
            set {
                this.hotelReservationIDField = value;
                this.RaisePropertyChanged("HotelReservationID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class BasicPropertyInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hotelCodeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class Total : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountAfterTaxField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double AmountAfterTax {
            get {
                return this.amountAfterTaxField;
            }
            set {
                this.amountAfterTaxField = value;
                this.RaisePropertyChanged("AmountAfterTax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class ResGlobalInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TimeSpan timeSpanField;
        
        private Total totalField;
        
        private BasicPropertyInfo basicPropertyInfoField;
        
        private HotelReservationIDs hotelReservationIDsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TimeSpan TimeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
                this.RaisePropertyChanged("TimeSpan");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Total Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BasicPropertyInfo BasicPropertyInfo {
            get {
                return this.basicPropertyInfoField;
            }
            set {
                this.basicPropertyInfoField = value;
                this.RaisePropertyChanged("BasicPropertyInfo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public HotelReservationIDs HotelReservationIDs {
            get {
                return this.hotelReservationIDsField;
            }
            set {
                this.hotelReservationIDsField = value;
                this.RaisePropertyChanged("HotelReservationIDs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class TimeSpan : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startField;
        
        private System.DateTime endField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class RoomStay : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TimeSpan timeSpanField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TimeSpan TimeSpan {
            get {
                return this.timeSpanField;
            }
            set {
                this.timeSpanField = value;
                this.RaisePropertyChanged("TimeSpan");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class UniqueID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private int idField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiteminderChannel : Test.SiteMinder.ISiteminder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteminderClient : System.ServiceModel.ClientBase<Test.SiteMinder.ISiteminder>, Test.SiteMinder.ISiteminder {
        
        public SiteminderClient() {
        }
        
        public SiteminderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteminderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteminderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteminderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRS(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRS(Request);
        }
        
        public System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRSAsync(Request);
        }
        
        public Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRSError(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRSError(Request);
        }
        
        public System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSErrorAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRSErrorAsync(Request);
        }
        
        public Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRSWarning(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRSWarning(Request);
        }
        
        public System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSWarningAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRSWarningAsync(Request);
        }
        
        public Test.SiteMinder.OTA_HotelResNotifRS OTA_HotelResNotifRSWarningAndError(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRSWarningAndError(Request);
        }
        
        public System.Threading.Tasks.Task<Test.SiteMinder.OTA_HotelResNotifRS> OTA_HotelResNotifRSWarningAndErrorAsync(Test.SiteMinder.OTA_HotelResNotifRQ Request) {
            return base.Channel.OTA_HotelResNotifRSWarningAndErrorAsync(Request);
        }
    }
}
